apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parallel-you-data-protection
  namespace: aetheric-forge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
