apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - deployment.yaml
  - service.yaml
  - data-protection-pvc.yaml

labels:
  - pairs:
      app.kubernetes.io/name: parallel-you
      app.kubernetes.io/part-of: aetheric-forge
      app.kubernetes.io/managed-by: kustomize
