apiVersion: v1
kind: Service
metadata:
  name: parallel-you
  namespace: aetheric-forge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: parallel-you
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
